version: "3.8"

services:
  app:
    container_name: youtubetrim
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "3007:3000"
    env_file: .env.production
    restart: unless-stopped
    volumes:
      - ./apps/server/downloads:/app/apps/server/downloads