name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    uses: marcusabu/workflows/.github/workflows/deploy.yml@main
    with:
      app_name: ${{ github.event.repository.name }}
    secrets:
      ssh_password: ${{ secrets.SSH_PASSWORD }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
